### ISSUE TITLE
아이폰에서 레이아웃 깨짐이 발생합니다.

### ISSUE THREAD

**Issue by ayaysir** [UmaSupporter/UmaSupporter.WebClient#56]
안녕하세요.
지나가던 우마 서포터 이용자입니다.
아이폰 XR을 사용하고 있는데 스크롤이 끝까지 되지 않고 레이아웃 밑부분의 내비게이션 부분이 보이지 않아
해결 요청하고자 합니다.

![uma1](https://user-images.githubusercontent.com/40187546/119640366-805be080-be53-11eb-8976-e1758f7d5a81.PNG)
![uma2](https://user-images.githubusercontent.com/40187546/119640389-86ea5800-be53-11eb-9e9e-5195689b0ac3.PNG)
아이폰 XR에서 빨간색 네모친 부분으로 스크롤이 더 이상 내려가지 않고, 밑의 내비게이션 부분이 보이지 않는 문제가 발생합니다. 

![uma3](https://user-images.githubusercontent.com/40187546/119640406-89e54880-be53-11eb-8522-f0587e959093.PNG)
![uma4](https://user-images.githubusercontent.com/40187546/119640413-8baf0c00-be53-11eb-9962-ccce4be4b697.PNG)
위 스크린샷처럼 해결되었으면 좋겠습니다. 

제가 나름대로 해결방법을 찾아본 결과 Scaffold.scss 파일의 `min-height` 부분이 문제인것을 찾았습니다.
풀 레퀘스트로 요청할까 하다 한 줄만 수정하는 부분이라 먼저 이슈 게시판으로 문의 드립니다.

src/components/common/Scaffold/Scaffold.scss 파일에서 `min-height` 부분을 변경해주시면 감사하겠습니다.

```
.Scaffold {
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: var(--background);
  // -webkit-fill-available 사용시 아이폰에서 레이아웃 꺠짐 발생
  min-height: -webkit-fit-content;
  padding: 0px 100px;
  justify-content: center;
}
```

번거롭게 해드려 죄송합니다.

**Comment by riemannulus** [comment]
제보 감사합니다!

**Comment by riemannulus** [comment]
#61 에서 @cereme 님이 기여해 주셨습니다.

**Comment by riemannulus** [comment]
@all-contributors please add @ayaysir for bug
