### ISSUE TITLE
아이패드에서 멀티윈도우로 이용시 탭간 간격이 늘어납니다.

### ISSUE THREAD

**Issue by homeownie** [UmaSupporter/UmaSupporter.WebClient#57]
https://cdn.discordapp.com/attachments/269717030117048326/847054471728857088/GIF_2021-05-26_7-00-54.gif

안녕하세요. 

다름이 아니구 안드로이드에서 이용할땐 못느꼈던 문제인데 ios(아이패드사용중입니다.) 기본 브라우저를 이용하여 서포터 이용시 
캐릭터/서포터 탭의 사이가 자꾸 늘어나서 화면 바깥으로 밀려난 서포터들을 선택 못하는 문제가 있어 제보드립니다.
사진 첨부가 잘 되었으려나 모르겠는데 캐릭터의 선택지들을 열어놓고서 서포터의 선택지를 보고 다른 서포터를 확인하려고 돌아가면 사이 간극이 엄청 벌어지더라구요.. 그상태서 캐릭터 메뉴도 뒤로 가보면 본래 두줄로 보였던 캐릭터가 4줄로 늘어나서 서포터들을 밀어냅니다.
위아래로 이동은 되는데 좌우로 바깥으로 밀려난 친구들은 좌우로 화면을 끌어보아도 보이질 않습니다.

제가 github은 처음 사용해보는지라 이슈 제보를 이렇게 하는게 맞나 잘 모르겠습니다.
부족한 글 읽어주시고, 수고해주심에 감사드립니다.

**Comment by riemannulus** [comment]
제보 감사합니다!
